spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/quartz
    username: postgres
    password: postgres
    type: org.postgresql.jdbc2.optional.PoolingDataSource
  batch:
    jdbc:
      initialize-schema: always
      platform: postgresql
    job:
      enabled: false
  liquibase:
    change-log: classpath*:db/changelog/changelog-master.xml

app:
  processing-delay: 3s
  job-cron: '*/1 * * * * *'
  lock:
    owner: localhost # has to be unique for every active instance, as lock is reentrant
    least: 2s
    most: 10s

logging:
  level:
    org.springframework.batch: warn
    ru.ins137.ru: info
